tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from tienda.views import TiendaView, BuscarView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', TiendaView.as_view(), name='index'),
    path('buscar/', BuscarView.as_view(), name='buscar'),
    path("carrito/", include ("carrito.urls")),
    path("catalogo/", include ("catalogo.urls")),
    path("pedidos/", include ("pedidos.urls")),
    path("usuarios/", include ("usuarios.urls")),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre_artista = models.CharField(max_length=255, verbose_name='Nombre del Artista')
    nombre_disco = models.CharField(max_length=255, default='Sin Nombre', verbose_name='Nombre del Disco')
    descripcion = models.TextField(blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Precio')
    stock = models.IntegerField()
    categoria = models.ForeignKey(Categoria, related_name="productos", on_delete=models.CASCADE)
    imagen_tapa = models.ImageField(upload_to='img/', blank=True, null=True) #Campo para la imagen del disco
        
    def __str__(self):
        return f'{self.nombre_artista} - {self.nombre_disco}'

usuarios/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El usuario debe tener un email.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255,unique=True)
    email = models.EmailField(unique=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    numero_de_telefono = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['nombre', 'apellido', 'email', 'numero_de_telefono', 'address']

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_superuser
    
    def has_module_perms(self, app_label):
        return self.is_superuser

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap" rel="stylesheet">
    {% block extra_head %}{% endblock %}
    <title>{% block title %}Tienda de Discos{% endblock %}</title>
</head>
<body>
    <div class="wrapper">
        <!-- Barra de Navegación -->
        {% block navbar %}
        <nav class="navbar">
            <div class="container">
                <h1 class="logo"><a href="{% url 'index' %}">MUSIK!</a></h1>
                
                <!-- Formulario de búsqueda -->
                <form action="{% url 'buscar' %}" method="GET" class="search-form">
                    <input type="text" name="q" placeholder="Buscar...">
                    <button type="submit">Buscar</button>
                </form>
                
                <ul class="nav-links">
                    <li><a href="{% url 'catalogo' %}">Catálogo</a></li>
                    <li><a href="{% url 'carrito' %}">Mi Carrito</a></li>
                    <li><a href="{% url 'pedidos' %}">Mis Pedidos</a></li>
                    <li><a href="{% url 'usuarios' %}">Usuario</a></li>
                </ul>
            </div>
        </nav>
        {% endblock %}
        
        <!-- Contenido específico de cada página -->
        <main class="content">
            {% block content %}{% endblock %}
        </main>
        
        <!-- Footer -->
        <footer class="footer">
            <div class="container">
                <p>&copy; 2024 <h3>MUSIK!</h3>   - Todos los derechos reservados.</p>
                <div class="social-links">
                    <a href="#">Facebook</a>
                    <a href="#">Twitter</a>
                    <a href="#">Instagram</a>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

templates/index.html
{%extends "base.html"%}
{%load static %}
{%block extra_head%}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap" rel="stylesheet">
{%endblock%}
{%block title%} Pagina principal de la tienda {%endblock%}
{%block content%}

<body>

    <div class="main-container">

        <div class="bienvenida-container">

            <div class="texto">
                <h1>BIENVENIDOS A</h1> <h2>Musik!</h2> 
                <p>En nuestro Shop vas a poder encontrar <br>CDs, DVDs, Vinilos y Bluray nuevos <br>(nacionales e importados), tanto <br> nuevos como usados. </p> <br>
                <a href="{% url 'catalogo' %}" class="explore-button">Explorar tienda</a>
                <a href="https://open.spotify.com/" class="explore-button">Popular albums</a>
            </div>

            <div class="imagenes">
                <img src="{% static 'image/portada.jpg' %}" alt="Discos de Música">
            </div>

        </div>

    </div>

</body>

{%endblock%}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block title %}Login{% endblock %}
{% block navbar %}{% endblock %}
{% block content %}
<div class="login-wrapper">
    <div class="login-container">
        <div class="authincation-content">
            <br>
            <h4 class="text-center mb-4">¿Tenés una cuenta?</h4>
            <form method="post">
                {% csrf_token %}
                {% for message in messages %}
                <div class="form-group mt-3">
                    <p class="error-message text-danger">{{ message }}</p>
                </div>
                {% endfor %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}"><strong>Usuario</strong></label>
                    <input
                        type="text"
                        class="form-control"
                        id="{{ form.username.id_for_label }}"
                        name="{{ form.username.name }}"
                        placeholder="Usuario"
                        value="{{ form.username.value }}"
                    />
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}"><strong>Contraseña</strong></label>
                    <input
                        type="password"
                        class="form-control"
                        id="{{ form.password.id_for_label }}"
                        name="{{ form.password.name }}"
                        placeholder="Contraseña"
                    />
                </div>
                <br>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary btn-block">Iniciar sesión</button>
                </div>
                <div class="new-account mt-3">
                    <p>
                        ¿Aún no tienes cuenta?
                        <a class="text-primary" href="{% url 'registro' %}">¡Crea una!</a>
                    </p>
                    <br>
                </div>
                <h2>Iniciar sesión con Google</h2>
                <a href="{% url 'social:begin' 'google-oauth2' %}">Iniciar sesión con Google</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/logout.html
{%extends "base.html"%}
{%load static %}
{%block extra_head%}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{%endblock%}
{%block title%} Logout {%endblock%}
{%block content%}

    <div class="container">
        <div class="logout-message">
            <h1>¡Has cerrado sesión correctamente!</h1>
            <p>Gracias por usar nuestro servicio. ¿Te gustaría iniciar sesión nuevamente?</p>
        </div>
        <div class="logout-links">
            <a href="{% url 'login' %}" class="btn btn-primary">Iniciar sesión nuevamente</a>
       </div>
    </div>
{% endblock %}

templates/registro.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/registro.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
{% endblock %}
{% block title %} Página principal de la tienda {% endblock %}

{% block navbar %}
<!-- sobrescribiendo el bloque de navbar para que no aparezca en esta página -->
{% endblock %}

{% block content %}
<body class="h-100">
    <div class="authincation h-100">
        <div class="container-fluid h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
                                    <h4 class="text-center mb-4">CREÁ TU CUENTA</h4>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="form-group">
                                                <label for="id_nombre"><strong>Nombre</strong></label>
                                                <input
                                                    type="text"
                                                    class="form-control"
                                                    id="id_nombre"
                                                    name="nombre"
                                                    placeholder="Nombre"
                                                    required
                                                />
                                            </div>
                                            <div class="form-group">
                                                <label for="id_apellido"><strong>Apellido</strong></label>
                                                <input
                                                    type="text"
                                                    class="form-control"
                                                    id="id_apellido"
                                                    name="apellido"
                                                    placeholder="Apellido"
                                                    required
                                                />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group">
                                                <label for="id_numero_de_telefono"><strong>Número de teléfono</strong></label>
                                                <input
                                                    type="text"
                                                    class="form-control"
                                                    id="id_numero_de_telefono"
                                                    name="numero_de_telefono"
                                                    placeholder="Número de teléfono"
                                                    required
                                                />
                                            </div>
                                            <div class="form-group">
                                                <label for="id_username"><strong>Usuario</strong></label>
                                                <input
                                                    type="text"
                                                    class="form-control"
                                                    id="id_username"
                                                    name="username"
                                                    placeholder="Usuario"
                                                    required
                                                />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group">
                                                <label for="id_address"><strong>Dirección</strong></label>
                                                <input
                                                    type="text"
                                                    class="form-control"
                                                    id="id_address"
                                                    name="address"
                                                    placeholder="Dirección"
                                                    required
                                                />
                                            </div>
                                            <div class="form-group">
                                                <label for="id_email"><strong>Email</strong></label>
                                                <input
                                                    type="email"
                                                    class="form-control"
                                                    id="id_email"
                                                    name="email"
                                                    placeholder="email@example.com"
                                                    required
                                                />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group">
                                                <label for="id_password1"><strong>Contraseña</strong></label>
                                                <input
                                                    type="password"
                                                    class="form-control"
                                                    id="id_password1"
                                                    name="password1"
                                                    placeholder="Contraseña"
                                                    required
                                                />
                                            </div>
                                            <div class="form-group">
                                                <label for="id_password2"><strong>Confirmar Contraseña</strong></label>
                                                <input
                                                    type="password"
                                                    class="form-control"
                                                    id="id_password2"
                                                    name="password2"
                                                    placeholder="Contraseña"
                                                    required
                                                />
                                            </div>
                                        </div>
                                        <br>
                                        <div class="text-center mt-4">
                                            <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
                                        </div>
                                    </form>
                                    <br>
                                    <div class="new-account mt-3">
                                        <p>¿Ya tenés una cuenta?   <a class="text-primary" href="{% url 'login' %}">   Inicia sesión   </a></p>
                                    </div>
                                    {% for message in messages %}
                                    <div class="form-group mt-3">
                                        <p class="error-message text-danger">{{ message }}</p>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}